version: '3.8'

services:
  htmltopdf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: htmltopdf-converter
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    volumes:
      # Optional: Mount a volume for logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/pdf/test"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security options
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN # Required for Chrome sandbox
    shm_size: 2gb # Increase shared memory for Chrome

networks:
  default:
    name: htmltopdf-network
